name: scheduler-ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('./packages/app/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: NPM Install App
        working-directory: ./packages/app
        run: npm ci

      - name: Run NPM Build
        working-directory: ./packages/app
        run: npm run build

      - name: Deploy to Firebase
        if: github.event_name == 'push'
        working-directory: ./packages/app
        run: npm run deploy ${{ secrets.FIREBASE_TOKEN }}
