name: scheduler-ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('./packages/app/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: NPM Install App
        working-directory: ./packages/app
        run: npm ci

      - name: Run NPM Build
        working-directory: ./packages/app
        run: npm run build

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.1
        with:
          GOOGLE_APPLICATION_CREDENTIALS: null
          FIREBASE_PROJECT_ID: "cable-scheduler"
          NEXT_PUBLIC_API_ENDPOINT_URL: "https://cable-scheduler.web.app/api/graphql"
          FIRESTORE_EMULATOR_HOST: null
          directory: "packages/app" 
          file_name: .env

      - name: Deploy to Firebase
        if: github.event_name == 'push'
        working-directory: ./packages/app
        run: npm run deploy ${{ secrets.FIREBASE_TOKEN }}
